dc/78_write_pod
anusii/solidpod pull request #115
Opened 2024-04-25 12:54 UTC by cdawei

# Pull Request Details

## What issue does this PR address

- Write data to POD

- Link to associated issue: #78

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the team style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

2024-04-26 01:59 UTC, gjwgit approved these changes

2024-04-26 23:18 UTC, gjwgit requested changes
Moving from dev to dc/78 I now get the following error in my app:

```
ERROR: lib/home.dart:81:50: Error: The operator '[]' isn't defined for the class '({String name, String version})'.
ERROR: Try correcting the operator to an existing operator, or defining a '[]' operator.
ERROR:                   applicationName: appNameVersion[0].toString(),
ERROR:                                                  ^
ERROR: lib/home.dart:82:53: Error: The operator '[]' isn't defined for the class '({String name, String version})'.
ERROR: Try correcting the operator to an existing operator, or defining a '[]' operator.
ERROR:                   applicationVersion: appNameVersion[1].toString(),
ERROR:                                                     ^
```

2024-04-29 01:52 UTC, cdawei commented
> Moving from dev to dc/78 I now get the following error in my app:
> 
> ```
> ERROR: lib/home.dart:81:50: Error: The operator '[]' isn't defined for the class '({String name, String version})'.
> ERROR: Try correcting the operator to an existing operator, or defining a '[]' operator.
> ERROR:                   applicationName: appNameVersion[0].toString(),
> ERROR:                                                  ^
> ERROR: lib/home.dart:82:53: Error: The operator '[]' isn't defined for the class '({String name, String version})'.
> ERROR: Try correcting the operator to an existing operator, or defining a '[]' operator.
> ERROR:                   applicationVersion: appNameVersion[1].toString(),
> ERROR:                                                     ^
> ```

The refactoring of `getAppnameVersion` in `solidpod` using [Dart Records](https://dart.dev/language/records#record-fields) in this branch means getting app name and version need to be done by:
```code
applicationName: appNameVersion.name,
applicationVersion: appNameVersion.version,
```

2024-05-01 00:50 UTC, gjwgit approved these changes

2024-05-01 01:19 UTC, junhaow1 approved these changes
works on chrome (Mac)

2024-05-01 02:38 UTC, merged