Zy/125 review structure
anusii/solidpod pull request #219
Opened 2024-07-29 05:00 UTC by zheyxu

# Pull Request Details

## What issue does this PR address

- Drop the Continue button

- Link to associated issue: https://github.com/anusii/keypod/issues/125

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the team style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

2024-07-29 05:52 UTC, gjwgit requested changes
DO NOT MERGE - a misunderstanding - we keep the CONTINUE button in SOLIDPOD but specify required: true in KEYPOD.

2024-07-29 06:17 UTC, zheyxu commented
> DO NOT MERGE - a misunderstanding - we keep the CONTINUE button in SOLIDPOD but specify required: true in KEYPOD.

Get it. The new implementation is that keep the CONTINUE button in SOLIDPOD. If specify required: true, the CONTINUE button is dropped. If specify required: false, the CONTINUE button is kept.

2024-08-01 23:57 UTC, anushkavidanage approved these changes

2024-08-02 00:39 UTC, zheyxu commented
Hi @gjwgit, make changes according to your request.

2024-08-07 00:34 UTC, gjwgit approved these changes

2024-08-07 00:34 UTC, merged