Zy/2 initialise pod
anusii/solidpod pull request #56
Opened 2024-02-15 00:44 UTC by anushkavidanage

# Pull Request Details
Merging the branch with dev to have the new package name `solidpod`

## What issue does this PR address
- resolving all the conflicts when merging from dev

- Link to associated issue: [#](https://github.com/anusii/solidpod/issues/2)

## Checklist

[Use the check-list below to ensure your branch is ready for PR]

- [ ] Changes adhere to the team style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint errors (`make prep` or `flutter analyze lib`
                       python: use pre-commit ruff hook to check on commit)
- [ ] No lint check errors related to your changes
- [ ] Tested on at least one device
      - [ ] Android Phone
      - [ ] Android Emulator
      - [ ] Chrome
      - [ ] iOS
      - [ ] Linux
      - [ ] MacOS
      - [ ] Windows
- [ ] Added 2 reviewers (or 1 for private repositories then they add another)

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number
- [ ] Merge PR into dev

2024-02-15 05:48 UTC, zheyxu approved these changes

2024-02-15 22:56 UTC, gjwgit commented on lib/src/solid/authenticate.dart
> +import 'package:flutter/material.dart';
This should be separate line and first.

2024-02-15 22:57 UTC, gjwgit commented on lib/src/solid/login.dart
>  import 'package:flutter/material.dart';
This is all correct re ordering imports - please follow this style.

2024-02-15 22:57 UTC, gjwgit commented on lib/src/solid/login.dart
>  import 'package:solidpod/src/solid/authenticate.dart';
Except these should be alphabetic.

2024-02-16 00:06 UTC, gjwgit requested changes
Please don't bring this into dev until it has been re-engineered. 

For example, initial_setup_desktop needs to be cleaned up and made a lot smaller.

`make prep` needs a lot of work. I did a `make fix` to autofix what can be done.

Great that it is functional though and we can test the initialise in this branch to at least unblock other tasks.

2024-02-22 06:38 UTC, anushkavidanage commented
@gjwgit I have now completely restructured the files for this functionality. Please have a look and let me know any changes are required.

2024-02-22 21:31 UTC, gjwgit commented
I am seeing this dependency issue - I've updated flutter to latest. Perhaps that caused it?

```
23 Feb 08:27:53 gjw@kadesh ~/projects/keypod$ ls
total 160K
4.0K analysis_options.yaml  4.0K build/        4.0K guidelines/   36K LICENSE       4.0K Makefile         0 solidpod@  4.0K windows/
4.0K android/               4.0K CHANGELOG.md  4.0K ios/         4.0K license.dart   36K pubspec.lock  4.0K support/
4.0K assets/                4.0K coverage/     4.0K keypod.iml   4.0K linux/        4.0K pubspec.yaml  4.0K test/
4.0K backup/                4.0K doc/          4.0K lib/         4.0K macos/        4.0K README.md     4.0K web/
23 Feb 08:29:26 gjw@kadesh ~/projects/keypod$ cd solidpod
/home/gjw/projects/keypod/solidpod
23 Feb 08:29:38 gjw@kadesh ~keypod/solidpod$ git pull
Already up to date.
23 Feb 08:29:43 gjw@kadesh ~keypod/solidpod$ git status
On branch zy/2_initialise_pod
Your branch is up to date with 'origin/zy/2_initialise_pod'.

nothing to commit, working tree clean
23 Feb 08:29:46 gjw@kadesh ~keypod/solidpod$ cd ..
23 Feb 08:29:52 gjw@kadesh ~/projects/keypod$ make linux
flutter run --device-id linux
Resolving dependencies... (1.0s)
Because solid_auth 0.1.13 depends on intl ^0.18.0 and no versions of solid_auth match >0.1.13 <0.2.0, solid_auth ^0.1.13 requires intl ^0.18.0.
And because every version of solidpod from path depends on intl ^0.19.0, solid_auth ^0.1.13 is incompatible with solidpod from path.
So, because keypod depends on solidpod from path which depends on solid_auth ^0.1.13, version solving failed.
make: *** [support/flutter.mk:92: linux] Error 1
23 Feb 08:30:26 gjw@kadesh ~/projects/keypod$ flutter --version
Flutter 3.19.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision abb292a07e (2 days ago) • 2024-02-20 14:35:05 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1
```

2024-02-22 22:01 UTC, anushkavidanage commented
Resolved this by lowering the `intl` version since not only `solid_auth`, but a few other packages also depend on `intl` 18.0.

2024-03-04 01:25 UTC, gjwgit approved these changes
Looking good. Thanks for that.

2024-03-04 23:18 UTC, gjwgit commented
With @anushkavidanage to merge the PR.

2024-03-06 23:06 UTC, merged