Av/28 initial gui for viewing data
anusii/solidpod pull request #69
Opened 2024-03-19 05:48 UTC by anushkavidanage

# Pull Request Details

## What issue does this PR address

- Initial GUI for viewing private data

- Link to associated issue: https://github.com/anusii/keypod/issues/28

## Checklist

[Use the check-list below to ensure your branch is ready for PR]

- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint errors (`make prep` or `flutter analyze lib`
                       python: use pre-commit ruff hook to check on commit)
- [x] No lint check errors related to your changes
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [x] Windows
- [ ] Added 2 reviewers (or 1 for private repositories then they add another)

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number
- [ ] Merge PR into dev

2024-03-19 06:26 UTC, gjwgit requested changes
With KeyPod, click continue then display data (first time without a keypod folder) I get the red screen:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building FutureBuilder<dynamic>(dirty, state:
_FutureBuilderState<dynamic>#5c59d):
type 'Null' is not a subtype of type 'String' in type cast

The relevant error-causing widget was:
  FutureBuilder<dynamic>
  FutureBuilder:file:///home/gjw/git/github/anusii/keypod/solidpod/lib/src/screens/view_data/view_keys.dart:69:13

When the exception was thrown, this was the stack:
#0      _ShowKeysState.build.<anonymous closure> (package:solidpod/src/screens/view_data/view_keys.dart:76:55)
#1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:609:55)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#12     _invoke (dart:ui/hooks.dart:312:13)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#14     _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════════════════════════
```



Testing with InnerPod, if I LOGIN then I see this as the app display.

![image](https://github.com/anusii/solidpod/assets/1681429/667bf4cb-9e07-42cd-91fe-b84ee25f1b55)

That seems correct, and nice to see the addition of the back arrow somehow?

When I click the Continue button (named SESSION for InnerPod) I don't get the back arrow?

![image](https://github.com/anusii/solidpod/assets/1681429/771247f2-2d3d-4192-ad71-f4e7318a7c7d)


Was the back arrow added by the solidpod package? Should it be there in both scenarios.

This is my SolidLogin screen: 
![image](https://github.com/anusii/solidpod/assets/1681429/a3430e2e-2244-41a3-87cf-30f8c234c4bd)

2024-03-19 06:26 UTC, gjwgit commented on lib/src/screens/view_data/view_keys.dart
Why is this in here? Shouldn't this be in the keypod app?

2024-03-19 19:00 UTC, gjwgit commented on lib/src/screens/view_data/view_keys.dart
The file name should match the main function name?

2024-03-21 05:25 UTC, anushkavidanage commented
Fixed discussed issues. @gjwgit please have a look and let me know if you see any other issues.

2024-03-21 10:20 UTC, gjwgit approved these changes
Tested with KeyPod. All good.

2024-03-21 23:06 UTC, junhaow1 commented
will review after the standup

2024-03-22 01:45 UTC, cdawei approved these changes
Worked in my test using the corresponding branch of keypod.

2024-03-22 01:47 UTC, junhaow1 approved these changes
works well on my machine.

2024-03-22 02:17 UTC, merged