Kev/72_74_ lint_warning
anusii/solidpod pull request #86
Opened 2024-03-25 02:22 UTC by junhaow1

# Pull Request Details

## What issue does this PR address

- [A one line description of this PR]

- Link to associated issue: #

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the team style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [ ] No lint check errors related to your changes (`make prep`)
- [ ] Pre-exisiting lint errors noted: 
- [ ] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [ ] Windows
- [ ] Added 2 reviewers

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Bump appropriate version and build number in pubspec.yaml
- [ ] Add one line summary into CHANGELOG.md
- [ ] Push to git repository and review
- [ ] Merge PR into dev

2024-03-25 05:59 UTC, cdawei approved these changes
Looks good. The commented out code may be deleted later if they won't be used.

2024-03-26 22:05 UTC, gjwgit requested changes
I was looking for the issues to be fixed, not marked for ignorance.

2024-03-26 22:05 UTC, gjwgit commented on lib/src/screens/initial_setup/initial_setup_constants.dart
> +// const kTitleTextColor = Color(0xFF30384D);
How does this affect the doc string just above? It may look somewhat odd in the generated docs?

2024-03-26 22:05 UTC, gjwgit commented on lib/src/screens/initial_setup/initial_setup_constants.dart
> +// const double kDefaultPadding = 20.0;
How does this affect the doc string just above? It may look somewhat odd in the generated docs?

2024-03-26 22:05 UTC, gjwgit commented on lib/src/screens/initial_setup/initial_setup_screen.dart
> +// const double normalLoadingScreenHeight = 200.0;
How does this affect the doc string just above? It may look somewhat odd in the generated docs?

2024-03-26 22:05 UTC, gjwgit commented on lib/src/screens/initial_setup/widgets/initial_setup_welcome.dart
> +/// // comment out the following function as it is not used in the current version
How does this affect the doc string? It may look somewhat odd in the generated docs?

2024-03-26 22:05 UTC, gjwgit commented on lib/src/screens/initial_setup/widgets/initial_setup_welcome.dart
> +/// // comment out the following function as it is not used in the current version
How does this affect the doc string? It may look somewhat odd in the generated docs?

2024-03-26 22:05 UTC, gjwgit commented on lib/src/solid/api/rest_api.dart
> +// ignore_for_file: comment_references
What and why?

2024-03-26 22:05 UTC, gjwgit commented on lib/src/solid/common_func.dart
> +// ignore_for_file: comment_references
What and why?

2024-03-26 22:05 UTC, gjwgit commented on lib/src/solid/common_func.dart
> +/// // comment out the following function as it is not used in the current version
Looks odd for docstring.

2024-03-26 22:05 UTC, gjwgit commented on lib/src/solid/constants.dart
> +// ignore_for_file: public_member_api_docs
What and why - we are looking for solutions, not ignoring problems!

2024-03-26 22:05 UTC, gjwgit commented on lib/src/solid/read_pod.dart
> +// ignore_for_file: use_build_context_synchronously
Solution, not ignore.

2024-03-27 03:08 UTC, gjwgit approved these changes
Perhaps merge for now and we'll fix up the specific issues in other tasks over time.

2024-03-27 04:19 UTC, anushkavidanage approved these changes

2024-03-27 04:20 UTC, anushkavidanage commented
Looks good from my side.

2024-03-27 04:26 UTC, merged